# Generated by Django 3.1.2 on 2020-11-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Bardzo łatwy', 'Very Easy'), ('Łatwy', 'Easy'), ('Średni', 'Normal'), ('Trudny', 'Difficult'), ('Bardzo trudny', 'Very Difficult')], default='Średni', max_length=20),
        ),
    ]
