# Generated by Django 3.1.2 on 2020-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0002_DifficultyEnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Normal'), (4, 'Difficult'), (5, 'Very Difficult')], default=3),
        ),
    ]
