# Generated by Django 3.1.2 on 2020-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0002_Comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.IntegerField(choices=[(1, 'Czasowa'), (2, 'Pora'), (3, 'Rodzaj'), (4, 'Kategoria')], default=4),
        ),
    ]
