# Generated by Django 3.1.2 on 2020-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('popcorn', '0003_DifficultyEnum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(
                choices=[(1, 'Bardzo łatwa'), (2, 'Łatwa'), (3, 'Średnia'), (4, 'Trudna'), (5, 'Bardzo trudna')],
                default=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='hidden_on',
            field=models.DateTimeField(null=True),
        ),
    ]
