# Generated by Django 3.1.2 on 2020-12-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0007_auto_20201204_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
