# Generated by Django 3.1.2 on 2020-12-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0007_auto_20201204_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newsletter_signup',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
