# Generated by Django 3.1.2 on 2020-12-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0008_auto_20201207_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
