# Generated by Django 3.1.2 on 2020-12-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0009_auto_20201207_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to='popcorn.moderator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to='popcorn.moderator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
