# Generated by Django 3.1.2 on 2020-12-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0008_auto_20201207_0937'),
        ('popcorn', '0012_auto_20201207_0914'),
    ]

    operations = [
    ]
