# Generated by Django 3.1.2 on 2020-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0013_merge_20201207_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Bardzo łatwa'), (2, 'Łatwa'), (3, 'Średnia'), (4, 'Trudna'), (5, 'Bardzo trudna')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
