# Generated by Django 3.1.2 on 2020-12-13 21:37

from django.db import migrations, models
import django.utils.timezone
import popcorn.models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0013_merge_20201207_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Bardzo łatwa'), (2, 'Łatwa'), (3, 'Średnia'), (4, 'Trudna'), (5, 'Bardzo trudna')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='recipes_icons', validators=[popcorn.models.validate_recipe_icon]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
