# Generated by Django 3.1.2 on 2020-12-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0014_auto_20201213_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
